create table if not exists public.usuarios (
  id bigint primary key,
  nome text not null,
  nicho text not null default '',
  nome_empresa text not null default '',
  email text not null unique,
  senha text not null,
  telefone text not null default '',
  tipo text not null check (tipo in ('Administrador', 'Cliente')),
  plano_tipo text not null default 'Producao de Conteudo' check (plano_tipo in ('Producao de Conteudo', 'Gestao de Trafego', 'Ambos'))
);

create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text not null default '',
  data date not null,
  hora time not null,
  tipo text not null default 'tarefa',
  status text not null default 'agendada',
  repeticao_tipo text not null default 'none',
  repeticao_intervalo integer not null default 1,
  repeticao_unidade text not null default 'none',
  repeticao_dias_semana text not null default '',
  repeticao_dia_mes integer,
  repeticao_fim date,
  evento_pai_id bigint references public.eventos(id) on delete cascade,
  data_original date,
  tipo_excecao text
);

create table if not exists public.eventos_clientes (
  evento_id bigint not null references public.eventos(id) on delete cascade,
  cliente_id bigint not null references public.usuarios(id) on delete cascade,
  primary key (evento_id, cliente_id)
);

create table if not exists public.conteudos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  tipo text not null,
  descricao text not null default '',
  link_drive text not null default '',
  data_publicacao date not null,
  data_criacao date not null default current_date,
  status text not null default 'pendente',
  cliente_id bigint not null references public.usuarios(id) on delete cascade
);

create table if not exists public.campanhas (
  id bigint generated by default as identity primary key,
  nome text not null,
  cliente_id bigint not null references public.usuarios(id) on delete cascade,
  orcamento numeric(14,2) not null default 0,
  plataforma text not null,
  data_inicio date not null,
  data_fim date not null,
  cliques integer not null default 0,
  impressoes integer not null default 0,
  conversoes integer not null default 0,
  custo_resultado numeric(14,2) not null default 0
);

create table if not exists public.financeiro_lancamentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text not null default '',
  valor numeric(14,2) not null default 0,
  tipo text not null
);

create index if not exists idx_usuarios_tipo on public.usuarios(tipo);
create index if not exists idx_eventos_data_hora on public.eventos(data, hora);
create index if not exists idx_eventos_pai_original on public.eventos(evento_pai_id, data_original);
create index if not exists idx_eventos_clientes_cliente on public.eventos_clientes(cliente_id);
create index if not exists idx_conteudos_cliente_data on public.conteudos(cliente_id, data_publicacao);
create index if not exists idx_campanhas_cliente_periodo on public.campanhas(cliente_id, data_inicio, data_fim);

alter table public.usuarios
  add column if not exists telefone text not null default '';

alter table public.usuarios
  add column if not exists nicho text not null default '';

alter table public.usuarios
  add column if not exists nome_empresa text not null default '';

alter table public.usuarios
  add column if not exists senha text not null default 'cliente123';

alter table public.usuarios
  add column if not exists tipo text not null default 'Cliente';

alter table public.usuarios
  add column if not exists plano_tipo text not null default 'Producao de Conteudo';

alter table public.eventos
  add column if not exists repeticao_tipo text not null default 'none';

alter table public.eventos
  add column if not exists repeticao_intervalo integer not null default 1;

alter table public.eventos
  add column if not exists repeticao_unidade text not null default 'none';

alter table public.eventos
  add column if not exists repeticao_dias_semana text not null default '';

alter table public.eventos
  add column if not exists repeticao_dia_mes integer;

alter table public.eventos
  add column if not exists repeticao_fim date;

alter table public.eventos
  add column if not exists evento_pai_id bigint references public.eventos(id) on delete cascade;

alter table public.eventos
  add column if not exists data_original date;

alter table public.eventos
  add column if not exists tipo_excecao text;

alter table public.conteudos
  add column if not exists data_criacao date not null default current_date;

alter table public.conteudos
  add column if not exists link_drive text not null default '';

alter table public.campanhas
  add column if not exists cliques integer not null default 0;

alter table public.campanhas
  add column if not exists impressoes integer not null default 0;

alter table public.campanhas
  add column if not exists conversoes integer not null default 0;

alter table public.campanhas
  add column if not exists custo_resultado numeric(14,2) not null default 0;

do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public'
      and table_name = 'tarefas'
  ) then
    insert into public.eventos (
      id,
      titulo,
      descricao,
      data,
      hora,
      tipo,
      status
    )
    select
      t.id,
      t.titulo,
      coalesce(t.descricao, ''),
      t.data,
      t.hora,
      coalesce(t.tipo, 'tarefa'),
      coalesce(t.status, 'agendada')
    from public.tarefas t
    on conflict (id) do nothing;
  end if;

  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public'
      and table_name = 'tarefas_clientes'
  ) then
    insert into public.eventos_clientes (evento_id, cliente_id)
    select tarefa_id, cliente_id
    from public.tarefas_clientes
    on conflict do nothing;
  end if;
end $$;
